#!/bin/bash

cd "$(git rev-parse --show-toplevel)" || exit 1

cd web-capture || exit 1
cargo clippy --fix --allow-dirty --allow-staged -- -D warnings || exit 1
cargo clippy -- -D warnings || exit 1
cd ..

./gradlew verifyAll || exit 1