[package]
name = "web_capture"
version = "0.1.0"
edition = "2024"

[lib]
name = "web_capture"
crate-type = ["cdylib"]
path = "src/rust/web_capture.rs"

[dependencies]
monolith = { package = "capture_core", git = "https://github.com/LinkoraApp/capture-core", branch = "base" }
jni = "0.21"
tokio = { version = "1.0", features = ["full"] }
dashmap = "6.2.1"

[dev-dependencies]
jni = { version = "0.21", features = ["invocation"] }
tempfile = "3.27.0"